version: "3.4"

services:
  redis:
    image: redis:alpine

  postgres:
    image: postgres:alpine
    env_file:
      - ./.env
    volumes:
      - ./pgdata:/var/lib/postgresql/data/

  web:
    image: django
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
    # ports:
    #   - 9001:8000

  celery:
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 9000:80
    depends_on:
      - web
